[project]
name = "modern-python"
version = "0.1.0"
description = ""
authors = [
    {name = "Miguel Villa Floran",email = "miguel.villafloran@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "paramiko (>=3.5.0,<4.0.0)",
    "requests (>=2.32.3,<3.0.0)"
]

[tool.poetry]
packages = [
    { include = "modern_python", from = "src" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
